# Use official lightweight Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy project files into the container
COPY . /app

# Install required libraries
RUN pip install --upgrade pip
RUN pip install opencv-python torch torchvision torchaudio ultralytics deep_sort_realtime

# Default command
CMD ["python", "object_detection_video.py"]
